version: "3.8"
services:
  myblog:
    build: .
    ports:
      - "3000:5000"
    volumes:
      - ./:/app
      - /app/node_modules

    environment:
      - PORT=5000
      #env_file:
      #- ./.env
