version: "3.8"
services:
  myblog:
    build: .
    ports:
      - "3000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: Hanbo
      MONGO_INITDB_ROOT_PASSWORD: lhb1999114
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
